-- First Time Run
-- dotnet ef dbcontext scaffold “Host=localhost;Database=collabtag;Username=postgres;Password=postgres” Npgsql.EntityFrameworkCore.PostgreSQL -o Models

-- Later Run
-- dotnet ef dbcontext scaffold “Host=localhost;Database=collabtag;Username=postgres;Password=postgres” Npgsql.EntityFrameworkCore.PostgreSQL -o Models -f


DROP TABLE IF EXISTS C_USER CASCADE;
DROP TABLE IF EXISTS MODEL CASCADE;
DROP TABLE IF EXISTS PROJECT CASCADE;
DROP TABLE IF EXISTS DATA CASCADE;
DROP TABLE IF EXISTS CLASS CASCADE;
DROP TABLE IF EXISTS MEMBER CASCADE;

-- USER TABLE
CREATE TABLE C_USER (
  ID_USER CHARACTER VARYING(255) NOT NULL,
  USERNAME CHARACTER VARYING(255) NOT NULL,
  EMAIL CHARACTER VARYING(255) NOT NULL,
  NAME CHARACTER VARYING(255),
  LASTNAME CHARACTER VARYING(255)
);

ALTER TABLE C_USER ADD CONSTRAINT USER_PK PRIMARY KEY  (ID_USER);

-- MODEL TABLE
CREATE TABLE MODEL (
    ID_MODEL BIGSERIAL NOT NULL,
    FILE BYTEA NOT NULL,
    ACCURACY REAL,
    DATE TIMESTAMP WITH TIME ZONE NOT NULL,
    ID_PROJECT BIGSERIAL NOT NULL
);

ALTER TABLE MODEL ADD CONSTRAINT MODEL_PK PRIMARY KEY (ID_MODEL);

-- PROJECT TABLE
CREATE TABLE PROJECT (
    ID_PROJECT BIGSERIAL NOT NULL,
    NAME CHARACTER VARYING(255) NOT NULL,
    DATE TIMESTAMP WITH TIME ZONE NOT NULL,
    DESCRIPTION CHARACTER VARYING(255),
    ID_USER CHARACTER VARYING(255) NOT NULL
);

ALTER TABLE PROJECT ADD CONSTRAINT PROJECT_PK PRIMARY KEY (ID_PROJECT);

-- DATA TABLE
CREATE TABLE DATA (
    ID_DATA BIGSERIAL NOT NULL,
    IMAGE BYTEA NOT NULL,
    DATE TIMESTAMP WITH TIME ZONE NOT NULL,
    ID_PROJECT BIGSERIAL NOT NULL,
    ID_USER CHARACTER VARYING(255) NOT NULL,
    ID_CLASS BIGINT NULL
);

ALTER TABLE DATA ADD CONSTRAINT DATA_PK PRIMARY KEY (ID_DATA);

-- CLASS TABLE
CREATE TABLE CLASS (
    ID_CLASS BIGSERIAL NOT NULL,
    NAME CHARACTER VARYING(255) NOT NULL,
    ID_PROJECT BIGSERIAL NOT NULL
);

ALTER TABLE CLASS ADD CONSTRAINT CLASS_PK PRIMARY KEY (ID_CLASS);

-- MEMBER TABLE
CREATE TABLE MEMBER (
    ID_MEMBER BIGSERIAL NOT NULL,
    ID_USER CHARACTER VARYING(255) NOT NULL,
    ID_PROJECT BIGSERIAL NOT NULL,
    DATE TIMESTAMP WITH TIME ZONE NOT NULL
);

ALTER TABLE MEMBER ADD CONSTRAINT MEMBER_PK PRIMARY KEY (ID_MEMBER);

-- ONE TO MANY RELATIONS
ALTER TABLE MODEL ADD CONSTRAINT MODEL_FK1 FOREIGN KEY (ID_PROJECT) REFERENCES PROJECT (ID_PROJECT);

ALTER TABLE PROJECT ADD CONSTRAINT PROJECT_FK1 FOREIGN KEY (ID_USER) REFERENCES C_USER (ID_USER);

ALTER TABLE CLASS ADD CONSTRAINT CLASS_FK1 FOREIGN KEY (ID_PROJECT) REFERENCES PROJECT (ID_PROJECT);

ALTER TABLE DATA ADD CONSTRAINT DATA_FK1 FOREIGN KEY (ID_USER) REFERENCES C_USER (ID_USER);
ALTER TABLE DATA ADD CONSTRAINT DATA_FK2 FOREIGN KEY (ID_CLASS) REFERENCES CLASS (ID_CLASS);
ALTER TABLE DATA ADD CONSTRAINT DATA_FK3 FOREIGN KEY (ID_PROJECT) REFERENCES PROJECT (ID_PROJECT);

ALTER TABLE MEMBER ADD CONSTRAINT MEMBER_FK1 FOREIGN KEY (ID_USER) REFERENCES C_USER (ID_USER);
ALTER TABLE MEMBER ADD CONSTRAINT MEMBER_FK2 FOREIGN KEY (ID_PROJECT) REFERENCES PROJECT (ID_PROJECT);


