-- DML
INSERT INTO C_USER (ID_USER, USERNAME, EMAIL, NAME, LASTNAME) VALUES ('dgNx8flhwAb2K1l8zMp9VYE1elp1', 'gallo', ' gallo@mail.com', 'Christian', 'Gallo');
INSERT INTO C_USER (ID_USER, USERNAME, EMAIL, NAME, LASTNAME) VALUES ('OR3MbEl4amRE6E69uBG97gwapbA3', 'sebas', 'sebas@mail.com', 'Sebastian', 'Garcia');
INSERT INTO C_USER (ID_USER, USERNAME, EMAIL, NAME, LASTNAME) VALUES ('I9Ga9E1Fc5Wb1mpPBJ37P0lrSsg1', 'nandito', 'juaferax@mail.com', 'Juan Fernando', 'Angulo');

INSERT INTO PROJECT (NAME, DATE, DESCRIPTION, ID_USER) VALUES ('Gallos Project', TO_DATE('23-04-2021', 'DD-MM-YYYY'), 'My project description', 'dgNx8flhwAb2K1l8zMp9VYE1elp1');
INSERT INTO PROJECT (NAME, DATE, DESCRIPTION, ID_USER) VALUES ('Sebas Project', TO_DATE('24-04-2021', 'DD-MM-YYYY'), 'A rock, paper, scissors project', 'I9Ga9E1Fc5Wb1mpPBJ37P0lrSsg1');

INSERT INTO MEMBER (ID_USER, ID_PROJECT, DATE) VALUES ('OR3MbEl4amRE6E69uBG97gwapbA3', '1', TO_DATE('25-04-2021', 'DD-MM-YYYY'));
INSERT INTO MEMBER (ID_USER, ID_PROJECT, DATE) VALUES ('I9Ga9E1Fc5Wb1mpPBJ37P0lrSsg1', '1', TO_DATE('28-04-2021', 'DD-MM-YYYY'));

INSERT INTO CLASS (NAME, ID_PROJECT) VALUES ('HIGH', 1);
INSERT INTO CLASS (NAME, ID_PROJECT) VALUES ('MEDIUM', 1);
INSERT INTO CLASS (NAME, ID_PROJECT) VALUES ('LOW', 1);

INSERT INTO CLASS (NAME, ID_PROJECT) VALUES ('ROCK', 2);
INSERT INTO CLASS (NAME, ID_PROJECT) VALUES ('PAPER', 2);
INSERT INTO CLASS (NAME, ID_PROJECT) VALUES ('SCISSORS', 2);

INSERT INTO DATA (IMAGE, DATE, ID_PROJECT, ID_USER) VALUES ('000', TO_DATE('30-04-2021', 'DD-MM-YYYY'), 1,'dgNx8flhwAb2K1l8zMp9VYE1elp1');
INSERT INTO DATA (IMAGE, DATE, ID_PROJECT, ID_USER) VALUES ('001', TO_DATE('30-04-2021', 'DD-MM-YYYY'), 1,'dgNx8flhwAb2K1l8zMp9VYE1elp1');
INSERT INTO DATA (IMAGE, DATE, ID_PROJECT, ID_USER) VALUES ('010', TO_DATE('30-04-2021', 'DD-MM-YYYY'), 1,'dgNx8flhwAb2K1l8zMp9VYE1elp1');
INSERT INTO DATA (IMAGE, DATE, ID_PROJECT, ID_USER, ID_CLASS) VALUES ('011', TO_DATE('30-04-2021', 'DD-MM-YYYY'), 1,'dgNx8flhwAb2K1l8zMp9VYE1elp1', 1);
INSERT INTO DATA (IMAGE, DATE, ID_PROJECT, ID_USER, ID_CLASS) VALUES ('100', TO_DATE('30-04-2021', 'DD-MM-YYYY'), 1,'dgNx8flhwAb2K1l8zMp9VYE1elp1', 2);
INSERT INTO DATA (IMAGE, DATE, ID_PROJECT, ID_USER, ID_CLASS) VALUES ('101', TO_DATE('30-04-2021', 'DD-MM-YYYY'), 1,'dgNx8flhwAb2K1l8zMp9VYE1elp1', 3);

INSERT INTO MODEL (FILE, ACCURACY, DATE, ID_PROJECT) VALUES ('111000', 97.0, TO_DATE('01-05-2021', 'DD-MM-YYYY'), 1);